services:
  web:
    build: pileofmediasite
    ports:
      - "443:443"
    volumes:
      - content:/usr/share/nginx/pileofmedia/content
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - content:/content/
    environment:
      SECRET: Placeholder
      CONTENT_DISPLAY_PATH: http://localhost:5000/images/
      DATABASE_URL: postgresql://postgres:Placeholder@db:5432/collectiondb
      SERVER_URL: http://localhost:5000/
      CONTENT_PATH: /content/
      API_URL: http://localhost:5000/api/
  db:
    build: database
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Placeholder

volumes:
  content:
  pg-data:

