[package]
name = "multipart"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["multipart"] }

[lib]
name = "multipart"
path = "lib.rs"

[lints]
workspace = true
