[package]
name = "repositories"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
domain = { path = "../domain" }

[lib]
name = "repositories"
path = "lib.rs"

[lints]
workspace = true
