pub mod default_book_repository;
pub mod default_genre_repository;
pub mod default_theme_repository;
pub mod default_person_repository;
pub mod default_character_repository;
pub mod default_book_relations_repository;
pub mod default_role_repository;
pub mod file_repository;
pub mod image_repository;
